# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

name: ${PROJECT_NAME}

services:
  isa:
    image: ${SRV_ISA_IMAGE_NAME}
    container_name: ${SRV_CONTAINER_NAME}
    hostname: ${SRV_HOSTNAME}
    ports:
      - ${SRV_PORT}:80
    volumes:
      - ${PROJECT_DIR}/test/isa:/test
      - ${PROJECT_DIR}/app/isa/isa:/usr/local/isa
      - ${PROJECT_DIR}/app/isa/modules:/usr/local/modules
      - ${PROJECT_DIR}/app/isa/configs:/usr/local/configs
      - ${PROJECT_DIR}/infra:/var/local/infra
      - ${PROJECT_DIR}/conf/docker/docker-compose-${SRV_HOSTNAME}.yml:/var/local/infra/host/docker-compose.yml
      - ${PROJECT_DIR}/cache/docker-compose-${SRV_HOSTNAME}.env:/var/local/infra/host/docker-compose.env
      - "//var/run/docker.sock:/var/run/docker.sock"
      - ${PROJECT_DIR}/cache/${SRV_HOSTNAME}:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /test
    networks:
      - srv-network

  server:
    image: ${SRV_INFRA_IMAGE_NAME}
    container_name: ${SRV_CONTAINER_NAME}_server
    volumes:
      - ${PROJECT_DIR}/app/dotnet:/usr/local/server
    networks:
      - srv-network

  tester:
    image: ${SRV_TESTER_IMAGE_NAME}
    container_name: ${SRV_CONTAINER_NAME}_tester
    volumes:
      - ${PROJECT_DIR}/test/tester:/usr/local/test
      - ${PROJECT_DIR}/cache/${SRV_HOSTNAME}:/tmp
    networks:
      - srv-network

networks:
  srv-network:
    driver: bridge
    name: ${INFRA_DOCKER_NETWORK}
    external: true
